"""
generate-index.py
Generates dist/index.html linking to all rendered PDFs.
Run from the repository root after PDFs have been copied to dist/.
"""
import os

topics = [
    ("01-algebra",      "Algebra"),
    ("02-functions",    "Functions"),
    ("03-trigonometry", "Trigonometry & Geometry"),
    ("04-vectors",      "Vectors & Linear Algebra"),
    ("05-calculus",     "Calculus"),
    ("06-statistics",   "Statistics"),
    ("07-probability",  "Probability & Combinatorics"),
    ("08-sequences",    "Sequences & Series"),
    ("09-complex",      "Complex Numbers"),
]

rows = ""
for folder, title in topics:
    lecture   = f"topics/{folder}/lecture.pdf"
    exercises = f"topics/{folder}/exercises.pdf"
    lec_link  = f'<a href="{lecture}">Lecture Notes</a>'  if os.path.exists(f"dist/{lecture}")  else "—"
    ex_link   = f'<a href="{exercises}">Exercises</a>'    if os.path.exists(f"dist/{exercises}") else "—"
    rows += f"    <tr><td>{title}</td><td>{lec_link}</td><td>{ex_link}</td></tr>\n"

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gymnasium Mathematics</title>
  <style>
    body  {{ font-family: -apple-system, sans-serif; max-width: 800px;
            margin: 3rem auto; padding: 0 1.5rem; color: #1e293b; }}
    h1    {{ font-size: 1.8rem; border-bottom: 2px solid #e2e8f0;
            padding-bottom: 0.5rem; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 1.5rem; }}
    th    {{ text-align: left; padding: 0.6rem 1rem;
            background: #1e3a5f; color: white; }}
    td    {{ padding: 0.6rem 1rem; border-bottom: 1px solid #e2e8f0; }}
    tr:hover td {{ background: #f8fafc; }}
    a     {{ color: #2563eb; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .meta {{ color: #64748b; font-size: 0.85rem; margin-top: 2rem; }}
  </style>
</head>
<body>
  <h1>Gymnasium Mathematics</h1>
  <table>
    <thead>
      <tr><th>Topic</th><th>Lecture Notes</th><th>Exercises</th></tr>
    </thead>
    <tbody>
{rows}    </tbody>
  </table>
  <p class="meta">Generated by GitHub Actions.</p>
</body>
</html>"""

os.makedirs("dist", exist_ok=True)
with open("dist/index.html", "w") as f:
    f.write(html)

print("dist/index.html written.")
